# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d847f9e0b39faaf7c3226f8399a9a635c5d7e920b9739f9ee6cab70fc835fa0eb32d132ca7393cb2bd5fb19e5d705826b8c4cd1ac637e096955fdc6384596f

test:
  secret_key_base: 604ebe508d5dde95750f4db1ec662b5df25f28a207550944c72cf9f7f354b6612618556a237b93f6010f2b5e1c36d639e122eb625501a0c68d0f97719612b41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
